config/routes.rb
Rails.application.routes.draw do

  devise_for :users

 root 'welcome#homepage'

  resource :news

  get 'news/index' => 'news#index', as: 'newsindex'
  get 'news/edit/:id' => 'news#edit', as: 'editnews'
  patch 'news/edit/:id', controller: 'news', action: :update

end

app/models/news.rb
class News < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :find_news, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @allnews = News.all
  end

  def show

  end

  def new
    @news = News.new
  end

  def create
    @news = News.new(news_params)
    if @news.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @newest = News.last
  end

  def update
    @remove_picture = params[:remove_picture]
    params
    if @news.update(news_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def destroy
    @news.destroy
    redirect_to root_path
  end

end

private

def news_params
  params.require(:news).permit(:title, :content, :picture, :remove_picture)
end

def find_news
  @news = News.find(params[:id])
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :save_ip
  def homepage
    @newest = News.last
  end

  def save_ip
    tracker = find_ip
    if tracker.nil?
      Tracker.create({:ip => request.remote_ip, :timestamp => DateTime.now})
      @showoverlay = true
    else
      if tracker.timestamp + 1.hour < DateTime.now
        @showoverlay = true
        tracker.update(timestamp: DateTime.now)
      else
      @showoverlay = false
        end
    end
  end

    def find_ip
      Tracker.find_by_ip(request.remote_ip)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/tracker_helper.rb
module TrackerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Handzeit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news/_simpleform.html.erb
<%= simple_form_for @news, url: news_path do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.file_field :picture %>
    <%= f.button :submit %>
<% end %>

app/views/news/edit.html.erb
<h1>News editieren: </h1>

<br>
<%= simple_form_for @news, html: { class: 'form-vertical' }, url: editnews_path do |f| %>
    <%= f.input :title, lable: 'Überschrift' %>
    <%= f.input :content, label: 'Text'%>
    <%= f.file_field :picture %>

    <h5>Aktuelles Bild:</h5>

    <%= image_tag(@newest.picture_url) if @newest.picture.present? %><br>
    <br>
<br>

    <p>
      <label>
        <%= f.check_box :remove_picture %>
        Bild löschen?
      </label>
    </p>
    <%= f.button :submit %>
<% end %>

<script>

  $(document).ready(function(){

    var datelist = 0;
    $( "#ck-button" ).click(function()  {
      if (datelist == 0){
        datelist = 1;
        alert( datelist );
      } else {
        datelist = 0;
        alert( datelist );
      }
      document.getElementById("remove_picture").value = datelist;
    });
  });
</script>

app/views/news/index.html.erb
<h1>Alle Neuigkeiten</h1><br>
<%= @allnews.each do |news| %>
    <%= news.title %><br>
    <%= news.content %><br><br>
    <%= image_tag(news.picture_url) if news.picture.present? %>
<% end %>

app/views/news/new.html.erb
Neuen Artikel verfassen <br>
<%= render 'simpleform'%>

app/views/welcome/_about.html.erb
<section class="no-padding" id="about">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading"><%= t 'about.sub_title' %></h2>
        <img src="assets/heidi.jpg" class="img-centered"  width="291" alt="Foto von Heidi Suter">
        <img src="assets/beat.jpg" class="img-centered" width="291" alt="Foto von Beat Suter">
        <hr class="primary">
            <h3>Allgemein sind wir...</h3>
            <p>verlässlich, zielorientiert, konsequent, integrativ, kreativ, kooperativ, stressresistent, begeisterungsfähig, zukunftsorientiert, lesefreudig, farbenliebend, anpassungsfähig, intuitiv, ausdauernd, gesellig, kinderliebend und wetterfest.</p>
            <h3>Speziell können wir...</h3>
            <p>Erfahrungen und Wissen weiter geben, beobachten, erzählen, beraten, besprechen, begleiten, durchhalten, begeistern, injizieren, träumen, inspirieren, planen, zeichnen, malen, logisch denken, strukturieren, texten, spontan handeln, durchhalten, abbauen, umbauen, putzen, improvisieren, kochen, backen, geniessen, jäten, gärtnern, stricken, nähen, flicken, reparieren, tanzen, musizieren, wandern, tandemfahren, einradfahren, skifahren, snowboarden, schneeschuhlaufen, zugfahren, autofahren, gleitschirmlen, schwimmen ...und faulenzen</p>
            <h3>Unbrauchbar sind wir...</h3>
            <p>an Stammtischrunden, als Fernsehkonsumenten, als Sportkommentatoren, als permanent Erreichbare und als Nacherzähler oder Gerüchteflüsterer</p>
            <h3>Konkret sind wir...</h3>
            <p>in einen weiteren neuen Lebensabschnitt eingetreten, wo die Pflicht aufgehört hat und das aktuell Antreibende und Begeisternde beginnen kann.<br>Wir wählen jetzt selber, wo wir künftig unsere Spuren hinterlassen möchten. Eine davon ist das Projekt Handzeit.<br>Wir sind Eltern und leidenschaftliche Grosseltern.</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_chainreaction.html.erb
<section class="bg-primary" id="chainreaction">
  <div class="container">
    <div class="row">
      <div class="service-box">
        <h2 class="section-heading">Kettenreaktionen selber bauen</h2>
        <hr class="light">
        <p>Tüftel- und Bauphasen mit all ihren Erfolgen und Misserfolgen werden über alle Sinne erlebt. Sie sind in verschiedenen Hirnarealen gespeichert und können als Kompetenzen und Erfahrungen bei neuen Herausforderungen wieder abgerufen werden.
          <br><br>Hände als Erweiterung des Denkens einsetzen und gleichzeitig handmotorische Fertigkeiten fördern.
          <br><br>Kettenreaktionen lassen sich mit vielerlei Materialien aus dem Haushalt zusammenstellen und bauen. Im Garten kann auch Wasser und Brennbares integriert werden.
          <br><br>Die Videosammlung zu diesem Thema inspiriert zu eigenen Kreationen.
        </p>

        <object width="400" height="295">
          <param name="movie" value="https://www.youtube.com/embed/GXrRC3pfLnE">
          <param name="allowFullScreen" value="true">
          <param name="allowscriptaccess" value="always">
          <iframe width="400" height="295" src="https://www.youtube.com/embed/GXrRC3pfLnE" frameborder="0" allowfullscreen></iframe>
          </embed>
        </object>

      </div>
    </div>
  </div>
</section>

app/views/welcome/_consulting.html.erb
<section class="bg-primary" id="consulting">
  <div class="container">
    <div class="row">
      <div class="service-box">
        <h2 class="section-heading">Beweglichkeit im Kopf und in den Gelenken</h2>
        <hr class="light">
        <p>Es ist uns ein grosses Anliegen, Aktivitäten bis ins hohe Alter zu entwickeln und zu erhalten. Balance und Gleichgewicht sind verlässliche Qualitäten, um möglichst unfallfrei alt werden zu können. <br>Auch Neues kann im Alter noch gelernt werden. Auch ein gealtertes Gehirn kann neue Areale erschliessen und mit neuen Synapsen vernetzen. So hat Beat im Alter von 60 Jahren gelernt, Einrad zu fahren. Es ist möglich! Nur Mut beim Aufbruch zu neuen Ufern.</p>
        <p><br/>Beraten und Anfertigen von Hilfestellungen und Arbeitserleichterungen bei nachlassender Selbstständigkeit</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_contact.html.erb
<section class="bg-primary" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Wie wir gefunden werden können</h2>
        <hr class="light">
      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <p>Telefon: 062 926 02 62 </p>
        <p>E-Mail: <a href="beat.a.suter@gmail.com">beat.a.suter@gmail.com</a></p>
        <p>E-Mail: <a href="heidi.a.suter@gmail.com">heidi.a.suter@gmail.com</a></p>
      </div>
      <div class="col-lg-4 col-lg-offset-2 text-center">
        <p>Beat & Heidi Suter<br>Hirzenbergstrasse 9<br>4800 Zofingen</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_culture.html.erb
<section class="no-padding" id="culture">
  <div class="container">
    <div class="row">
      <div class="service-box">
        <h2 class="section-heading">Die Kultur der Reperatur</h2>
        <hr class="primary">
        <p class="text-muted">"Wir sind industrielle Analphabeten geworden. Es fehlt uns an Wissen, und oft fehlt auch das Werkzeug."<div class="quote">Wolfgang M. Heckl, Autor von "Die Kultur der Reperatur"</div></p>
        <p>Beraten und Anfertigen von Hilfestellungen und Arbeitserleichterungen bei nachlassender Selbstständigkeit</p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_header.html.erb
<header>
  <div class="header-content">
    <div class="header-content-inner">
      <div class="handzeit">

      </div>

    </div>

  </div>
  <div class="cpyright">
  © Ficht Tanner
</div>
</header>

app/views/welcome/_links.html.erb
<section class="no-padding" id="links">
  <div class="container">
    <div class="row">
      <div class="service-box">
        <h2 class="section-heading">Links</h2>
        <hr class="primary">
        <ul>
          <li><a href="https://youtu.be/1TwIUgd7eb0">Das Handwerk</a></li>
          <li><a href="http://www.fhnw.ch/ph/zntd/lehrpersonen/mobilab">Mobilab der FHNW</a></li>
          <li><a href="http://www.konsumentenschutz.ch/repaircafe">Repaircafés</a></li>
        </ul>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_nav.html.erb
<nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only"><%= t 'nav.toggle' %></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand page-scroll" href="#page-top"><%= t 'nav.main' %></a>
    </div>
    <% if @showoverlay == true %>

        <script type="text/javascript" >
          toggleOverlay();
        </script>

    <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li>
          <%= link_to "News editieren", editnews_path(@newest) %>
        </li>
        <% end %>
        <li>
            <a href='#' onclick='toggleOverlay()'>News</a>
        </li>
        <li>
          <a class="page-scroll" href="#about"><%= t 'nav.about' %></a>
        </li>
        <li>
          <a class="page-scroll" href="#contact"><%= t 'nav.contact' %></a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container-fluid -->
</nav>

app/views/welcome/_news.html.erb
<div id="overlay">
  <div>
    <div id="specialBox">
      <br>
      <button type="button" class="btn btn-info" onmousedown="toggleOverlay()">News schliessen</button><br>
      <p><h1><%= @newest.title %></h1>
      <p class="news" ><%= @newest.content.html_safe %></p>
      </p><br>
      <%= image_tag(@newest.picture_url) if @newest.picture.present? %>
    </div>
  </div>
</div>

app/views/welcome/_portfolio.html.erb
<section class="no-padding" id="portfolio">
  <div class="container-fluid">
    <div class="row no-gutter">
      <div class="col-lg-4 col-sm-6">
        <a href="#chainreaction" class="portfolio-box">
          <img src="assets/portfolio/1.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Kettenreaktionen selber bauen
              </div>
              <div class="project-name">
                zur Anleitung
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="#weather" class="portfolio-box">
          <img src="assets/portfolio/2.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Wetter
              </div>
              <div class="project-name">
                Das Wetter kennen lernen
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="#time" class="portfolio-box">
          <img src="assets/portfolio/3.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Zeit
              </div>
              <div class="project-name">
                Zeit und Zeitmessen
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="#" class="portfolio-box">
          <img src="assets/portfolio/4.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Zeit für die Hände
              </div>
              <div class="project-name">
                Das Handwerk
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="#consulting" class="portfolio-box">
          <img src="assets/portfolio/5.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Beweglichkeit
              </div>
              <div class="project-name">
                im Kopf und in den Gelenken
              </div>
            </div>
          </div>
        </a>
      </div>
      <div class="col-lg-4 col-sm-6">
        <a href="#culture" class="portfolio-box">
          <img src="assets/portfolio/6.jpg" class="img-responsive" alt="">
          <div class="portfolio-box-caption">
            <div class="portfolio-box-caption-content">
              <div class="project-category text-faded">
                Kultur
              </div>
              <div class="project-name">
                der Reparatur
              </div>
            </div>
          </div>
        </a>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_services.html.erb
<section id="services">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading"><%= t 'services.heading'%></h2>
        <hr class="primary">
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-diamond wow bounceIn text-primary"></i>
          <h3><%= t 'services.title.box1' %></h3>
          <p class="text-muted"><%= t 'services.text.box3' %></p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-paper-plane wow bounceIn text-primary" data-wow-delay=".1s"></i>
          <h3><%= t 'services.title.box2' %></h3>
          <p class="text-muted"><%= t 'services.text.box3' %></p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-newspaper-o wow bounceIn text-primary" data-wow-delay=".2s"></i>
          <h3><%= t 'services.title.box3' %></h3>
          <p class="text-muted"><%= t 'services.text.box3' %></p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 text-center">
        <div class="service-box">
          <i class="fa fa-4x fa-heart wow bounceIn text-primary" data-wow-delay=".3s"></i>
          <h3><%= t 'services.title.box4' %></h3>
          <p class="text-muted"><%= t 'services.text.box4' %></p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_time.html.erb
<section class="no-padding" id="time">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Zeit, Zeitmesser</h2>
        <hr class="primary">
          <img src="assets/handkreis.png" class="img-centered" width="420" alt="Kreis aus 12 sich ineinander greifenden Händen">
            <p class="text-muted">
          In den frühen achtziger Jahren entstand bei uns ein Buch zum Bau einfacher Wetterbeobachtungsgeräte. In der Folge planten wir etwas Ähnliches zur Zeitmessung. Das haben wir dann verworfen, weil schon viel zu diesem Thema auf dem Markt war.
          <br>
          Fragen in diesem Zusammenhang sind jedoch bis heute unbeantwortet. Eine davon ist die  grosse gedankliche Übereinstimmung von menschlichen Händen und der Einteilung der Welt in die  360° Winkelgrade der Geometrie, und daraus abgeleitet, die heutigen Zifferblätter von analogen Uhren.
          Menschen haben mit Sicherheit schon vor tausenden von Jahren den Körper als Masseinheiten benutzt. So entstanden Ellen und Fuss, während die Zeiteinteilung offenbar nach Massgabe der Finger entstanden sein kann.
          Auf babylonischen Tontafeln wurden solche Dokumente bei Ausgrabungen gefunden. Vor über 5000 Jahren verwendeten die Bewohner des eurasischen Halbmondes, zu dem auch das antike Babylon gehörte, für die Zeitmessung Zahlenfolgen die im Sonnensystem UND bei den Menschen zu finden sind.
          Mit den heute gebräuchlichen 360° Winkelgraden für eine tägliche Erddrehung näherten sie sich schon dem Jahr mit den 365 Tagen und den 12 monatlichen Mondphasen im Kalenderjahr. Diese Grundannahmen wurden von den Ägyptern, den Griechen und den Römern weitgehend übernommen und verfeinert. Parallel zu dieser Entwicklung verbreitete sich in der Mathematik das Dezimalsystem.
          Alle Versuche die Uhrzeit ins Dezimalsystem zu übertragen sind bis heute gescheitert.<br>
          Erst in unserer immer schneller werdenden Zeit wurden Hundertstel- und Tausendstelsekunden erfunden.</p>
          <img src="assets/hand_skizze.jpg" class="img-centered" width="420" alt="Skizze einer Hand mit abgespreizten Fingern. Der Winkelzwischenraum der Finger beträgt 15 Grad.">
          <p class="text-muted">
          In einer Hand mit gespreizten Fingern sind plus-minus immer noch etwa 15° Winkelgrade üblich. Das entspricht der am Himmel beobachtbaren stündlichen Bewegung der Sonne.
          Kombiniert mit einem Fixpunkt, einem Berg, einer Behausung oder einem Baum kann so der Lauf
          der Zeit beobachtet werden.<br>
          180° von Sonnenaufgang bis Sonnenuntergang und weitere 180° bis die Sonne wieder aufgeht, ergibt
          die 360° des Kreises.
          <br>
          Nach Massgabe der Finger und der Beobachtung der Sonne und des Mondes sind die Grundlagen
          für unsere heute gebräuchlichen Uhren mit Zifferblättern entstanden.<br>
          Eine Hand-Zeit-Uhr eben.<br>
          Ein Beweis für unsere These ist im Foto oben nachzuzählen:
          <br>
          12 Hände sind 60 Finger, die Hände stehen für die Stunden, die Finger für die Minuten.
          <br>
          Sachverhalte und Zusammenhänge, welche einen Bezug von Händen zu Zifferblättern aufzeigen, haben wir auch in grösseren Werken zur Geschichte der Zeitmessung keine gefunden.
          <br>
          Dass man mit den Händen rechnen kann, weiss jedes Kind. Bezüge zu Händen und Zeitrechnungen haben wir jedoch in keinem uns bekannten Mathe-Lehrmittel gefunden.
          Die grosse Ausnahme in unserem Dezimalsystem, das Sechzigersystem der Zeit und des Kreises, sind doch handfest und ganz Nahe bei uns selber zu finden. In solchen Zusammenhängen erlebt, ist der allgegenwärtige Umgang mit Zeit viel begreifbarer.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/welcome/_weather.html.erb
<section class="no-padding" id="weather">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 text-center">
        <h2 class="section-heading">Wetter, Wetterbeobachtung</h2>
        <hr class="primary">
        <img src="assets/pdf/station.jpg" width="80%" alt="Aeste pdf preview on link">
        <br/>
        <p>Mit dem Wetter sind wir jeden Tag konfrontiert. Wetterabläufe bleiben auch in Zukunft schwierig zu prognostizieren. Der Schulweg ist die letze Freiheit der Kinder, wo sie nicht direkt überwacht werden. Elterntaxis auf dem Schulweg und zu den verschiedenen Freizeitaktivitäten verunmöglichen den Kindern eine tägliche, spielerische Auseinandersetzung mit dem Phänomen des Wetters.<br>Die Klimaerwärmung und die mit ihr verbundenen Veränderungen ist Tatsache! Wetter findet im Freien statt und ist zu erforschen, zu erleben mit allen Sinnen und zu beobachten.<br>Eine Sensibilisierung zum Wettergeschehen ist mit alltäglichen Produkten und einfachen Haushaltswerkzeugen möglich.</p>
        <div id="pdfInARow">
            <a href="assets/pdf/Aeste.pdf" alt="Aeste pdf link">
              <div id="wrapper">
                <img src="assets/pdf/preview/aeste.jpg" alt="Aeste pdf preview on link">
                <p class="text">PDF öffnen</p>
              </div>
            </a>
            <a href="assets/pdf/Lufth.pdf" alt="Lufth pdf link">
              <div id="wrapper">
                <img src="assets/pdf/preview/lufth.jpg" alt="Lufth pdf preview on link">
                <p class="text">PDF öffnen</p>
              </div>
            </a>
            <a href="assets/pdf/Feucht.pdf" alt="Feutigkeit pdf link">
              <div id="wrapper">
                <img src="assets/pdf/preview/feuchtigkeit.jpg" alt="feuchtigkeit pdf preview on link">
                <p class="text">PDF öffnen</p>
              </div>
            </a>
            <a href="assets/pdf/Temp.pdf" alt="Temperatur pdf link">
              <div id="wrapper">
                <img src="assets/pdf/preview/temperatur.jpg" alt="temperatur pdf preview on link">
                <p class="text">PDF öffnen</p>
              </div>
            </a>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/welcome/homepage.html.erb
<!DOCTYPE html>
<html lang="de">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><%= t 'page_title' %></title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="assets/bootstrap.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="assets/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="assets/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>

    <![endif]-->

</head>

<body id="page-top">

    <%= render :partial => "news" %>

    <%= render :partial => "nav" %>

    <%= render :partial => "header" %>

    <%= render :partial => "time_for_hands" %>

    <%= render :partial => "portfolio" %>

    <%= render :partial => "time" %>

    <%= render :partial => "consulting" %>

    <%= render :partial => "about" %>

    <%= render :partial => "lable" %>

    <%= render :partial => "weather" %>

    <%= render :partial => "chainreaction" %>

    <%= render :partial => "links" %>

    <%= render :partial => "contact" %><br>
    <%= link_to "Admin", user_session_path %> <%= link_to('Logout', destroy_user_session_path, :method => :delete) %><br>
    <%= @newest.title %>

    <!-- jQuery -->
    <script src="assets/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="assets/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="assets/jquery.easing.min.js"></script>
    <script src="assets/jquery.fittext.js"></script>
    <script src="assets/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="assets/creative.js"></script>

</body>

</html>